name: image_libera
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.16.0-0 <3.0.0'
  flutter: ^2.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - res/blue_angel_2560x1440.jpg

flutter_icons:
#  android: launcher_icon
#  ios: true
  web: true
  image_path: res/blue_angel_2560x1440.jpg
